// CW-014 — Security Administrator on user or group principal
// Ported verbatim from:
//   internal/scan/embedded_rules/CW-014-security-administrator-user-group.yaml
//
// NOTE: CW-014 and CW-015 share the SAME role GUID (Security Administrator,
// 194ae4cb-b126-40b2-bd5b-6091b380977d) but have different principalFilter.types.
// CW-014 covers user + group (medium severity).
// CW-015 covers servicePrincipal + managedIdentity (high severity).

export default {
  id: 'CW-014',
  name: 'Security Administrator on user or group principal',
  version: '1.0.0',
  severity: 'medium',
  category: 'entra',
  plane: 'entra',
  tags: [
    'entra',
    'defense-evasion',
    'security-tooling',
    'single-role',
  ],
  description:
    'The Security Administrator role in Microsoft Entra ID grants the ability to dismiss\n' +
    'alerts in Microsoft Defender XDR, modify Defender for Cloud security configurations,\n' +
    'modify Identity Protection risk policies, and manage security-related Conditional\n' +
    'Access policy types. A principal holding this role can suppress active detections,\n' +
    'weaken security coverage, and reduce the fidelity of risk-based enforcement --\n' +
    'without triggering role-assignment audit events or touching authentication\n' +
    'credentials.\n' +
    '\n' +
    'This is a defense-evasion surface. The role does not grant direct privilege\n' +
    'escalation or credential injection capability (those are covered separately by\n' +
    'CW-011 for role assignment authority and CW-012 for Conditional Access policy\n' +
    'modification). Security Administrator is distinctive because it operates on the\n' +
    'security tooling layer itself: an attacker who holds this role can dismiss the\n' +
    'alerts generated by their own activity, weaken the detection policies that would\n' +
    'surface their behavior, and reduce the sensitivity of risk scoring that would\n' +
    'trigger step-up authentication challenges against their sessions.\n' +
    '\n' +
    'The role is genuinely required for security operations team members. For human user\n' +
    'and group principals, the rule\'s purpose is to verify that the assignment is\n' +
    'intentional and documented, not to imply ongoing attack. Most findings against\n' +
    'human users will be resolved with "yes, this is the SOC team lead; here is the\n' +
    'change ticket." The value of the rule is forcing that justification into an explicit\n' +
    'review rather than allowing the assignment to persist unexamined.\n' +
    '\n' +
    'This rule covers user and group principals only. When a service principal or managed\n' +
    'identity holds Security Administrator, CW-015 fires at high severity, reflecting that\n' +
    'no legitimate operational case exists for service principal Security Administrator as\n' +
    'a permanent active assignment -- programmatic alert dismissal and detection\n' +
    'configuration changes with no human review represent a substantially different risk\n' +
    'profile from the same capability held by a human analyst.',

  principalFilter: {
    types: ['user', 'group'],
  },

  requires: [
    {
      roleDefinitionId: '194ae4cb-b126-40b2-bd5b-6091b380977d',
      roleName: 'Security Administrator',
      scopeBinding: 'A',
      plane: 'entra',
    },
  ],

  scopeSemantics: { inheritance: 'respect' },

  finding: {
    title: 'Security Administrator assigned to user or group',
    summary:
      '{{.principal.display_name}} holds the Security Administrator role in the Entra ' +
      'directory (scope: {{.scope.A.id}}). This role grants the ability to dismiss alerts ' +
      'in Microsoft Defender XDR, modify Defender for Cloud security configurations, and ' +
      'modify Identity Protection risk policies. Verify that this assignment is intentional, ' +
      'documented, and scoped to a designated security operations team member.',
    remediationSummary:
      'Confirm this assignment is documented and intentional. Security Administrator is ' +
      'legitimately required for security operations team members; the finding\'s purpose ' +
      'is to surface unreviewed assignments, not to imply attack. If the assignment is ' +
      'legitimate, document the justification and consider converting the permanent active ' +
      'assignment to a Privileged Identity Management eligible assignment. If the assignment ' +
      'cannot be attributed to a named security team member with a documented operational ' +
      'need, remove it. Service principal assignments of this role are detected separately ' +
      'by CW-015 at higher severity.',
    remediationSteps: [
      'Confirm the identity of this principal and verify they are a designated member of the security operations team with a documented need for Security Administrator authority. Assignments that cannot be attributed to a specific operational role should be treated as unauthorized.',
      'For user principals with a confirmed operational need, consider converting the permanent active assignment to a Privileged Identity Management (PIM) eligible assignment. Configure time-bound activation and MFA enforcement at minimum; an approval workflow is recommended for assignments to roles with alert-dismissal authority.',
      'For group assignments, review the group\'s membership and confirm that every member of the group has an individual operational need for Security Administrator. Overly broad group membership is a common source of unintended Security Administrator exposure.',
      'Enable audit logging for all Defender XDR alert dismissals, Defender for Cloud configuration changes, and Identity Protection policy modifications made by this principal. Any configuration change that reduces detection coverage or suppresses active alerts should be reviewed as part of routine governance.',
      'Service principal assignments of this role are detected separately by CW-015 with higher severity, as service principals have no legitimate operational case for Security Administrator as a permanent active assignment.',
    ],
    remediationCli: [
      '# List active directory role assignments for this principal to find the assignment ID\n' +
      'az rest \\\n' +
      '  --method GET \\\n' +
      '  --url "https://graph.microsoft.com/v1.0/roleManagement/directory/roleAssignments?\\$filter=principalId eq \'{{.principal.object_id}}\' and roleDefinitionId eq \'194ae4cb-b126-40b2-bd5b-6091b380977d\'"',
      '# Remove the role assignment (replace {assignmentId} with the id from the query above)\n' +
      'az rest \\\n' +
      '  --method DELETE \\\n' +
      '  --url "https://graph.microsoft.com/v1.0/roleManagement/directory/roleAssignments/{assignmentId}"',
    ],
  },

  references: {
    microsoft: [
      'https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/permissions-reference',
    ],
    mitreAttack: ['T1562.001'],
  },

  provenance: {
    added: '2026-05-14',
    addedBy: 'Initial rule set',
    lastReviewed: '2026-05-14',
  },
};
